apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cms-nfs
  namespace: argocd
spec:
  project: default
  destination:
    namespace: cms
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    chart: nfs-subdir-external-provisioner
    helm:
      parameters:
        - name: nfs.server
          value: "10.148.0.25"
        - name: nfs.path
          value: "/mnt/sharedfolder"
        - name: storageClass.name
          value: "studio-nfs-client"
        - name: storageClass.provisionerName
          value: "k8s-sigs.io/second-nfs-subdir-external-provisioner"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true