{{ if and .Values.storageClass }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "cms.fullname" . }}-nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: "{{ .Values.storageClass }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
{{ end }}
