apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo-cd
spec:
  project: infrastructure
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: v1.9.5
    chart: ingress-nginx/ingress-nginx
    helm:
      parameters: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true